Fix for below errors that showed up after updating to latest MSVC.
tbprobe.cpp(1156): error C2672: 'search': no matching overloaded function found
tbprobe.cpp(1198): error C2783: 'Tablebases::WDLScore `anonymous-namespace'::search(Position &,Tablebases::ProbeState *)': could not deduce template argument for 'CheckZeroingMoves'

No functional change.

bench: 5244314